name: 'gitbook-build-actions'
on:
  push:
    branches:
      - main  # trigger branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Build and Deploy                  # https://github.com/ZanderZhao/gitbook-action/releases
      uses: ZanderZhao/gitbook-action@v1.2.4  # -> or ZanderZhao/gitbook-action@master.  If not use master click above, use latest please 
      with:                                   #    or fork this repo and use YourName/gitbook-action@master
        token: ${{ secrets.GITBOOK_PUBLIC }}  # -> remember add this in settings/secrets as following
        time_zone: Asia/Shanghai              # set time zone
        source_branch: main                   # clone source master
        source_dir: /                         # clone from source
        # source_edit_time: true              # source time
        publish_dir: /
        publish_cname: docs.roc.games
        publish_branch: gh-pages
        publish_push_force: true
        # publish_commit_message: ${{ github.event.head_commit.message }}  # use last commit message